
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `databasename_DBLINK`
--

DELIMITER $$
--
-- Functions
--
CREATE DEFINER=`databasename`@`localhost` FUNCTION `F_CLIENTS_PASSWORD_CHECK` (`P_CLIENT_EMAIL` VARCHAR(256), `P_CLIENT_PASSWORD` VARCHAR(256), `P_USER_IP` VARCHAR(16)) RETURNS INT BEGIN
DECLARE  V_CLIENTID INT;
DECLARE  V_RETURNER INT;
DECLARE  V_SOUCCESS INT;
     SET V_CLIENTID = (   SELECT `KRN_CLIENTS`.`ID` FROM `KRN_CLIENTS`  WHERE `KRN_CLIENTS`.`CLIENT_EMAIL` =  P_CLIENT_EMAIL);
        
IF (V_CLIENTID IS NOT NULL) THEN
BEGIN 

IF (SELECT 1=1 FROM `KRN_CLIENTS` WHERE `KRN_CLIENTS`.`CLIENT_EMAIL` = P_CLIENT_EMAIL AND `KRN_CLIENTS`.`CLIENT_PASSWORD`=SHA1(P_CLIENT_PASSWORD)) THEN
BEGIN
UPDATE `KRN_CLIENTS`  
SET `KRN_CLIENTS`.`CLIENT_ATTEMPTS` = 0,
`KRN_CLIENTS`.`LAST_LOGIN` = NOW()
WHERE `KRN_CLIENTS`.`ID` = V_CLIENTID;
SET V_SOUCCESS = 1;
SET V_RETURNER = 1;
END;
ELSE 
BEGIN
UPDATE `KRN_CLIENTS` A
INNER JOIN `KRN_CLIENTS` B ON A.`ID` =  B.`ID`
SET A.`CLIENT_ATTEMPTS` = B.`CLIENT_ATTEMPTS`+1
WHERE A.`ID` = V_CLIENTID;
SET V_SOUCCESS = -1;
SET V_RETURNER = 0;
END;
END IF;

INSERT INTO `KRN_CLIENT_VERIFY_HIST`(
    `KRN_CLIENT_VERIFY_HIST`.`CLIENT_ID`,
    `KRN_CLIENT_VERIFY_HIST`.`VERIDY_COUNT`,
    `KRN_CLIENT_VERIFY_HIST`.`USER_IP`,
    `KRN_CLIENT_VERIFY_HIST`.`V_SOUCCESS`)
    SELECT 
    `KRN_CLIENTS`.`ID`,
    `KRN_CLIENTS`.`CLIENT_ATTEMPTS`,
    P_USER_IP,
    V_SOUCCESS 
    FROM `KRN_CLIENTS` WHERE `KRN_CLIENTS`.`ID` = V_CLIENTID;


END;
ELSE 
BEGIN
SET V_RETURNER = -1;
END;
END IF;

    RETURN V_RETURNER;
END$$

CREATE DEFINER=`databasename`@`localhost` FUNCTION `F_CLIENT_NEW_TOKEN` (`P_CLIENT_ID` INT) RETURNS VARCHAR(256) CHARSET utf8mb4 BEGIN
        DECLARE
        V_RETURNER VARCHAR(256);
IF (SELECT 1=1 FROM `KRN_CLIENTS` WHERE `KRN_CLIENTS`.`ID` = P_CLIENT_ID)
THEN
BEGIN
    INSERT INTO `KRN_CLIENT_TOKEN`(`KRN_CLIENT_TOKEN`.`CLIENT_ID`)
VALUES(P_CLIENT_ID) ;
SET V_RETURNER = (SELECT
    `KRN_CLIENT_TOKEN`.`TOKEN`
FROM
    `KRN_CLIENT_TOKEN`
WHERE
    `KRN_CLIENT_TOKEN`.`CLIENT_ID` = P_CLIENT_ID
ORDER BY
    `KRN_CLIENT_TOKEN`.`ID`
DESC
LIMIT 0, 1  );
END;
ELSE 
SET V_RETURNER = '';
END IF;
RETURN V_RETURNER;
END$$

DELIMITER ;

-- --------------------------------------------------------

--
-- Table structure for table `KRN_CLIENTS`
--

CREATE TABLE `KRN_CLIENTS` (
  `ID` int NOT NULL,
  `CLIENT_NAME` varchar(64) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `CLIENT_LASTNAME` varchar(64) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `CLIENT_EMAIL` varchar(124) NOT NULL,
  `CLIENT_PASSWORD` varchar(64) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `CLIENT_ATTEMPTS` int NOT NULL DEFAULT '0',
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_LOGIN` timestamp NULL DEFAULT NULL,
  `IACTIVE` int NOT NULL DEFAULT '0',
  `VERIFY` int NOT NULL DEFAULT '0',
  `CLASS` int NOT NULL DEFAULT '1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `KRN_CLIENTS`
--

INSERT INTO `KRN_CLIENTS` (`ID`, `CLIENT_NAME`, `CLIENT_LASTNAME`, `CLIENT_EMAIL`, `CLIENT_PASSWORD`, `CLIENT_ATTEMPTS`, `CREATE_DATE`, `LAST_LOGIN`, `IACTIVE`, `VERIFY`, `CLASS`) VALUES
(2, 'ADMIN', 'ADMIN', 'ADMIN@MAIL.COM', 'f7a4d1bdd232bb18b429df307f9a75c8940bb7f8', 0, '2023-02-03 20:34:37', '2023-02-03 20:41:59', 0, 0, 2);

--
-- Triggers `KRN_CLIENTS`
--
DELIMITER $$
CREATE TRIGGER `trigger_krn_clients_passowrd_hash` BEFORE INSERT ON `KRN_CLIENTS` FOR EACH ROW BEGIN
SET NEW.`CLIENT_PASSWORD` = (SELECT SHA1(NEW.`CLIENT_PASSWORD`));
END
$$
DELIMITER ;

-- --------------------------------------------------------

--
-- Table structure for table `KRN_CLIENTS_HIST`
--

CREATE TABLE `KRN_CLIENTS_HIST` (
  `ID` int NOT NULL,
  `CLIENT_ID` int NOT NULL,
  `OLD_DATA` json NOT NULL,
  `NEW_DATA` json NOT NULL,
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATE_USER` varchar(64) NOT NULL DEFAULT 'NO_USER'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

--
-- Table structure for table `KRN_CLIENT_CLASS`
--

CREATE TABLE `KRN_CLIENT_CLASS` (
  `ID` int NOT NULL,
  `CLASS_NAME` varchar(50) NOT NULL,
  `CLASS_DESC` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `KRN_CLIENT_CLASS`
--

INSERT INTO `KRN_CLIENT_CLASS` (`ID`, `CLASS_NAME`, `CLASS_DESC`) VALUES
(1, 'GUEST', 'not registered'),
(2, 'USER', 'registered'),
(3, 'EMPLOYEE', 'EMPLOYEE LEVEL1'),
(4, 'MANAGER', 'EMPLOYEE LEVEL2'),
(5, 'ADMIN', 'EMPLOYEE LEVEL3');

-- --------------------------------------------------------

--
-- Table structure for table `KRN_CLIENT_TOKEN`
--

CREATE TABLE `KRN_CLIENT_TOKEN` (
  `ID` int NOT NULL,
  `CLIENT_ID` int NOT NULL,
  `TOKEN` varchar(256) NOT NULL,
  `CREATE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EXPIRE` timestamp NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `KRN_CLIENT_TOKEN`
--

INSERT INTO `KRN_CLIENT_TOKEN` (`ID`, `CLIENT_ID`, `TOKEN`, `CREATE_DATE`, `EXPIRE`) VALUES
(9, 2, '362b5ab5cb7d7f830df1c21a9e3d3a10', '2023-02-03 21:02:23', '2023-02-03 22:02:23');

--
-- Triggers `KRN_CLIENT_TOKEN`
--
DELIMITER $$
CREATE TRIGGER `trigger_krn_client_token_expire` BEFORE INSERT ON `KRN_CLIENT_TOKEN` FOR EACH ROW BEGIN
  SET NEW.`EXPIRE` = DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL 60 MINUTE);
  END
$$
DELIMITER ;
DELIMITER $$
CREATE TRIGGER `trigger_krn_client_token_generate` BEFORE INSERT ON `KRN_CLIENT_TOKEN` FOR EACH ROW BEGIN
    SET @CHECKER = 1;
    WHILE (@CHECKER IS NOT NULL) DO 
  SET NEW.`TOKEN` = substr(md5(CURRENT_TIMESTAMP()+rand()),1,256);
      SET @CHECKER = (SELECT ID FROM `KRN_CLIENT_TOKEN` WHERE `TOKEN` = NEW.`TOKEN`);
      END WHILE;
  END
$$
DELIMITER ;

-- --------------------------------------------------------

--
-- Table structure for table `KRN_CLIENT_VERIFY_HIST`
--

CREATE TABLE `KRN_CLIENT_VERIFY_HIST` (
  `ID` int NOT NULL,
  `CLIENT_ID` int NOT NULL,
  `VERIDY_COUNT` int NOT NULL,
  `USER_IP` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `SOUCCESS` int NOT NULL,
  `DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `KRN_CLIENT_VERIFY_HIST`
--

INSERT INTO `KRN_CLIENT_VERIFY_HIST` (`ID`, `CLIENT_ID`, `VERIDY_COUNT`, `USER_IP`, `SOUCCESS`, `DATE`) VALUES
(4, 2, 1, '127.0.0.1', -1, '2023-02-03 20:41:47'),
(5, 2, 0, '192.168.0.1', -1, '2023-02-03 20:41:59');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `KRN_CLIENTS`
--
ALTER TABLE `KRN_CLIENTS`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `CLASS` (`CLASS`);

--
-- Indexes for table `KRN_CLIENTS_HIST`
--
ALTER TABLE `KRN_CLIENTS_HIST`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `CLIENT_ID` (`CLIENT_ID`);

--
-- Indexes for table `KRN_CLIENT_CLASS`
--
ALTER TABLE `KRN_CLIENT_CLASS`
  ADD PRIMARY KEY (`ID`);

--
-- Indexes for table `KRN_CLIENT_TOKEN`
--
ALTER TABLE `KRN_CLIENT_TOKEN`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `TOKEN` (`TOKEN`),
  ADD KEY `CLIENT_ID` (`CLIENT_ID`);

--
-- Indexes for table `KRN_CLIENT_VERIFY_HIST`
--
ALTER TABLE `KRN_CLIENT_VERIFY_HIST`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `CLIENT_ID` (`CLIENT_ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `KRN_CLIENTS`
--
ALTER TABLE `KRN_CLIENTS`
  MODIFY `ID` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `KRN_CLIENTS_HIST`
--
ALTER TABLE `KRN_CLIENTS_HIST`
  MODIFY `ID` int NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `KRN_CLIENT_CLASS`
--
ALTER TABLE `KRN_CLIENT_CLASS`
  MODIFY `ID` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `KRN_CLIENT_TOKEN`
--
ALTER TABLE `KRN_CLIENT_TOKEN`
  MODIFY `ID` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- AUTO_INCREMENT for table `KRN_CLIENT_VERIFY_HIST`
--
ALTER TABLE `KRN_CLIENT_VERIFY_HIST`
  MODIFY `ID` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `KRN_CLIENTS`
--
ALTER TABLE `KRN_CLIENTS`
  ADD CONSTRAINT `KRN_CLIENTS_ibfk_1` FOREIGN KEY (`CLASS`) REFERENCES `KRN_CLIENT_CLASS` (`ID`);

--
-- Constraints for table `KRN_CLIENTS_HIST`
--
ALTER TABLE `KRN_CLIENTS_HIST`
  ADD CONSTRAINT `KRN_CLIENTS_HIST_ibfk_1` FOREIGN KEY (`CLIENT_ID`) REFERENCES `KRN_CLIENTS` (`ID`);

--
-- Constraints for table `KRN_CLIENT_TOKEN`
--
ALTER TABLE `KRN_CLIENT_TOKEN`
  ADD CONSTRAINT `KRN_CLIENT_TOKEN_ibfk_1` FOREIGN KEY (`CLIENT_ID`) REFERENCES `KRN_CLIENTS` (`ID`);

--
-- Constraints for table `KRN_CLIENT_VERIFY_HIST`
--
ALTER TABLE `KRN_CLIENT_VERIFY_HIST`
  ADD CONSTRAINT `KRN_CLIENT_VERIFY_HIST_ibfk_1` FOREIGN KEY (`CLIENT_ID`) REFERENCES `KRN_CLIENTS` (`ID`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
